#!/bin/bash
mongoimport --db meteor --collection companies --type json --headerline --file 'CompanyNames.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection TWOGO --type json --headerline --file '2GO.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection AB --type json --headerline --file 'AB.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection ABA --type json --headerline --file 'ABA.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection ABG --type json --headerline --file 'ABG.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection ABS --type json --headerline --file 'ABS.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection ABSP --type json --headerline --file 'ABSP.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection AC --type json --headerline --file 'AC.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection ACE --type json --headerline --file 'ACE.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection ACPB1 --type json --headerline --file 'ACPB1.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection ACPB2 --type json --headerline --file 'ACPB2.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection ACR --type json --headerline --file 'ACR.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection AEV --type json --headerline --file 'AEV.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection AGI --type json --headerline --file 'AGI.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection ALCO --type json --headerline --file 'ALCO.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection ALHI --type json --headerline --file 'ALHI.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection ALI --type json --headerline --file 'ALI.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection ALT --type json --headerline --file 'ALT.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection ANI --type json --headerline --file 'ANI.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection ANS --type json --headerline --file 'ANS.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection AP --type json --headerline --file 'AP.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection APC --type json --headerline --file 'APC.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection APO --type json --headerline --file 'APO.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection APX --type json --headerline --file 'APX.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection AR --type json --headerline --file 'AR.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection ARA --type json --headerline --file 'ARA.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection AT --type json --headerline --file 'AT.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection ATI --type json --headerline --file 'ATI.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection ATN --type json --headerline --file 'ATN.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection ATNB --type json --headerline --file 'ATNB.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection AUB --type json --headerline --file 'AUB.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection BCB --type json --headerline --file 'BCB.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection BCOR --type json --headerline --file 'BCOR.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection BDO --type json --headerline --file 'BDO.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection BEL --type json --headerline --file 'BEL.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection BHI --type json --headerline --file 'BHI.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection BKR --type json --headerline --file 'BKR.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection BLFI --type json --headerline --file 'BLFI.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection BLOOM --type json --headerline --file 'BLOOM.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection BPI --type json --headerline --file 'BPI.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection BRN --type json --headerline --file 'BRN.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection BSC --type json --headerline --file 'BSC.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection CAL --type json --headerline --file 'CAL.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection CAT --type json --headerline --file 'CAT.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection CDC --type json --headerline --file 'CDC.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection CEB --type json --headerline --file 'CEB.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection CEI --type json --headerline --file 'CEI.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection CHI --type json --headerline --file 'CHI.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection CHIB --type json --headerline --file 'CHIB.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection CIC --type json --headerline --file 'CIC.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection CNPF --type json --headerline --file 'CNPF.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection COAL --type json --headerline --file 'COAL.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection COL --type json --headerline --file 'COL.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection COSCO --type json --headerline --file 'COSCO.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection CPG --type json --headerline --file 'CPG.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection CPM --type json --headerline --file 'CPM.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection CYBR --type json --headerline --file 'CYBR.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection DAVIN --type json --headerline --file 'DAVIN.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection DD --type json --headerline --file 'DD.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection DFNN --type json --headerline --file 'DFNN.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection DIZ --type json --headerline --file 'DIZ.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection DMC --type json --headerline --file 'DMC.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection DMPL --type json --headerline --file 'DMPL.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection DNL --type json --headerline --file 'DNL.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection ECP --type json --headerline --file 'ECP.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection EDC --type json --headerline --file 'EDC.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection EEI --type json --headerline --file 'EEI.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection EG --type json --headerline --file 'EG.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection ELI --type json --headerline --file 'ELI.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection EMP --type json --headerline --file 'EMP.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection EVER --type json --headerline --file 'EVER.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection EW --type json --headerline --file 'EW.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection FAF --type json --headerline --file 'FAF.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection FDC --type json --headerline --file 'FDC.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection FEU --type json --headerline --file 'FEU.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection FFI --type json --headerline --file 'FFI.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection FGEN --type json --headerline --file 'FGEN.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection FGENF --type json --headerline --file 'FGENF.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection FLI --type json --headerline --file 'FLI.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection FMETF --type json --headerline --file 'FMETF.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection FNI --type json --headerline --file 'FNI.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection FOOD --type json --headerline --file 'FOOD.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection FPH --type json --headerline --file 'FPH.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection FPI --type json --headerline --file 'FPI.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection GEO --type json --headerline --file 'GEO.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection GERI --type json --headerline --file 'GERI.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection GLO --type json --headerline --file 'GLO.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection GLOPP --type json --headerline --file 'GLOPP.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection GMA7 --type json --headerline --file 'GMA7.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection GMAP --type json --headerline --file 'GMAP.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection GREEN --type json --headerline --file 'GREEN.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection GSMI --type json --headerline --file 'GSMI.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection GTCAP --type json --headerline --file 'GTCAP.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection H2O --type json --headerline --file 'H2O.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection HI --type json --headerline --file 'HI.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection HLCM --type json --headerline --file 'HLCM.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection HOUSE --type json --headerline --file 'HOUSE.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection I --type json --headerline --file 'I.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection ICT --type json --headerline --file 'ICT.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection IMI --type json --headerline --file 'IMI.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection ION --type json --headerline --file 'ION.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection IPM --type json --headerline --file 'IPM.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection IPO --type json --headerline --file 'IPO.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection IRC --type json --headerline --file 'IRC.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection IS --type json --headerline --file 'IS.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection ISM --type json --headerline --file 'ISM.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection JAS --type json --headerline --file 'JAS.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection JFC --type json --headerline --file 'JFC.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection JGS --type json --headerline --file 'JGS.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection LAND --type json --headerline --file 'LAND.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection LBC --type json --headerline --file 'LBC.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection LC --type json --headerline --file 'LC.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection LCB --type json --headerline --file 'LCB.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection LIB --type json --headerline --file 'LIB.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection LIHC --type json --headerline --file 'LIHC.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection LMG --type json --headerline --file 'LMG.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection LOTO --type json --headerline --file 'LOTO.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection LPZ --type json --headerline --file 'LPZ.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection LR --type json --headerline --file 'LR.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection LRI --type json --headerline --file 'LRI.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection LRP --type json --headerline --file 'LRP.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection LRW --type json --headerline --file 'LRW.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection LSC --type json --headerline --file 'LSC.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection LTG --type json --headerline --file 'LTG.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection MA --type json --headerline --file 'MA.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection MAB --type json --headerline --file 'MAB.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection MAC --type json --headerline --file 'MAC.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection MARC --type json --headerline --file 'MARC.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection MAXS --type json --headerline --file 'MAXS.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection MB --type json --headerline --file 'MB.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection MBT --type json --headerline --file 'MBT.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection MCP --type json --headerline --file 'MCP.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection MED --type json --headerline --file 'MED.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection MEG --type json --headerline --file 'MEG.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection MER --type json --headerline --file 'MER.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection MFC --type json --headerline --file 'MFC.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection MG --type json --headerline --file 'MG.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection MJC --type json --headerline --file 'MJC.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection MPI --type json --headerline --file 'MPI.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection MRC --type json --headerline --file 'MRC.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection MVC --type json --headerline --file 'MVC.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection MWC --type json --headerline --file 'MWC.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection MWIDE --type json --headerline --file 'MWIDE.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection MWP --type json --headerline --file 'MWP.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection NI --type json --headerline --file 'NI.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection NIKL --type json --headerline --file 'NIKL.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection NOW --type json --headerline --file 'NOW.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection NRCP --type json --headerline --file 'NRCP.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection OM --type json --headerline --file 'OM.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection OPM --type json --headerline --file 'OPM.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection OPMB --type json --headerline --file 'OPMB.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection ORE --type json --headerline --file 'ORE.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection OV --type json --headerline --file 'OV.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection PA --type json --headerline --file 'PA.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection PAL --type json --headerline --file 'PAL.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection PBB --type json --headerline --file 'PBB.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection PBC --type json --headerline --file 'PBC.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection PCOR --type json --headerline --file 'PCOR.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection PERC --type json --headerline --file 'PERC.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection PF --type json --headerline --file 'PF.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection PFP --type json --headerline --file 'PFP.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection PGOLD --type json --headerline --file 'PGOLD.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection PHA --type json --headerline --file 'PHA.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection PHES --type json --headerline --file 'PHES.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection PHN --type json --headerline --file 'PHN.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection PIP --type json --headerline --file 'PIP.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection PLC --type json --headerline --file 'PLC.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection PMPC --type json --headerline --file 'PMPC.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection PNB --type json --headerline --file 'PNB.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection PNX --type json --headerline --file 'PNX.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection POPI --type json --headerline --file 'POPI.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection PPREF --type json --headerline --file 'PPREF.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection PRF2B --type json --headerline --file 'PRF2B.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection PRIM --type json --headerline --file 'PRIM.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection PRMX --type json --headerline --file 'PRMX.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection PSB --type json --headerline --file 'PSB.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection PSE --type json --headerline --file 'PSE.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection PSPC --type json --headerline --file 'PSPC.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection PX --type json --headerline --file 'PX.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection PXP --type json --headerline --file 'PXP.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection RCB --type json --headerline --file 'RCB.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection REG --type json --headerline --file 'REG.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection RFM --type json --headerline --file 'RFM.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection RLC --type json --headerline --file 'RLC.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection ROCK --type json --headerline --file 'ROCK.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection ROX --type json --headerline --file 'ROX.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection RRHI --type json --headerline --file 'RRHI.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection RWM --type json --headerline --file 'RWM.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection SCC --type json --headerline --file 'SCC.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection SECB --type json --headerline --file 'SECB.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection SFI --type json --headerline --file 'SFI.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection SGI --type json --headerline --file 'SGI.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection SHNG --type json --headerline --file 'SHNG.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection SLF --type json --headerline --file 'SLF.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection SLI --type json --headerline --file 'SLI.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection SM --type json --headerline --file 'SM.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection SMC --type json --headerline --file 'SMC.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection SMC2A --type json --headerline --file 'SMC2A.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection SMC2B --type json --headerline --file 'SMC2B.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection SMC2C --type json --headerline --file 'SMC2C.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection SMPH --type json --headerline --file 'SMPH.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection SOC --type json --headerline --file 'SOC.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection SPH --type json --headerline --file 'SPH.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection SSI --type json --headerline --file 'SSI.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection STI --type json --headerline --file 'STI.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection STR --type json --headerline --file 'STR.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection SUN --type json --headerline --file 'SUN.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection T --type json --headerline --file 'T.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection TA --type json --headerline --file 'TA.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection TAPET --type json --headerline --file 'TAPET.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection TECH --type json --headerline --file 'TECH.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection TEL --type json --headerline --file 'TEL.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection TFHI --type json --headerline --file 'TFHI.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection TUGS --type json --headerline --file 'TUGS.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection UBP --type json --headerline --file 'UBP.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection UNI --type json --headerline --file 'UNI.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection UPM --type json --headerline --file 'UPM.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection URC --type json --headerline --file 'URC.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection V --type json --headerline --file 'V.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection VITA --type json --headerline --file 'VITA.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection VLL --type json --headerline --file 'VLL.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection VMC --type json --headerline --file 'VMC.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection VUL --type json --headerline --file 'VUL.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection WEB --type json --headerline --file 'WEB.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection WIN --type json --headerline --file 'WIN.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection WPI --type json --headerline --file 'WPI.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection X --type json --headerline --file 'X.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection YEHEY --type json --headerline --file 'YEHEY.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection ZHI --type json --headerline --file 'ZHI.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection AAA --type json --headerline --file 'AAA.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection AGF --type json --headerline --file 'AGF.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection BC --type json --headerline --file 'BC.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection CEU --type json --headerline --file 'CEU.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection DWC --type json --headerline --file 'DWC.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection MACAY --type json --headerline --file 'MACAY.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection MFIN --type json --headerline --file 'MFIN.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection MHC --type json --headerline --file 'MHC.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection MJIC --type json --headerline --file 'MJIC.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection PAX --type json --headerline --file 'PAX.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection RLT --type json --headerline --file 'RLT.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection SEVN --type json --headerline --file 'SEVN.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection TBGI --type json --headerline --file 'TBGI.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection FGENG --type json --headerline --file 'FGENG.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection GPH --type json --headerline --file 'GPH.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection MEGW2 --type json --headerline --file 'MEGW2.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection PRF2A --type json --headerline --file 'PRF2A.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection SPM --type json --headerline --file 'SPM.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection VVT --type json --headerline --file 'VVT.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection CA --type json --headerline --file 'CA.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection CPVB --type json --headerline --file 'CPVB.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection JOH --type json --headerline --file 'JOH.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection KPHB --type json --headerline --file 'KPHB.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection LFM --type json --headerline --file 'LFM.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection PRC --type json --headerline --file 'PRC.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection RCI --type json --headerline --file 'RCI.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection SPC --type json --headerline --file 'SPC.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection BMM --type json --headerline --file 'BMM.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection CIP --type json --headerline --file 'CIP.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection FJP --type json --headerline --file 'FJP.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection CPV --type json --headerline --file 'CPV.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection EURO --type json --headerline --file 'EURO.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection BH --type json --headerline --file 'BH.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection KEP --type json --headerline --file 'KEP.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection PTC --type json --headerline --file 'PTC.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection SGP --type json --headerline --file 'SGP.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection TFC --type json --headerline --file 'TFC.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection KPH --type json --headerline --file 'KPH.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection FPHPC --type json --headerline --file 'FPHPC.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection IMP --type json --headerline --file 'IMP.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection CSB --type json --headerline --file 'CSB.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection SFIP --type json --headerline --file 'SFIP.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection IMPB --type json --headerline --file 'IMPB.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection FJPB --type json --headerline --file 'FJPB.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection PFP2 --type json --headerline --file 'PFP2.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection PPC --type json --headerline --file 'PPC.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection MBC --type json --headerline --file 'MBC.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection CROWN --type json --headerline --file 'CROWN.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection BCP --type json --headerline --file 'BCP.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection SBS --type json --headerline --file 'SBS.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection SMC2D --type json --headerline --file 'SMC2D.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection SMC2E --type json --headerline --file 'SMC2E.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection SMC2F --type json --headerline --file 'SMC2F.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection MRSGI --type json --headerline --file 'MRSGI.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection IDC --type json --headerline --file 'IDC.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection PNX3A --type json --headerline --file 'PNX3A.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection PNX3B --type json --headerline --file 'PNX3B.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection FINANCIAL --type json --headerline --file '^FINANCIAL.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection HOLDING --type json --headerline --file '^HOLDING.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection INDUSTRIA --type json --headerline --file '^INDUSTRIA.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection MININGOI --type json --headerline --file '^MINING-OI.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection PROPERTY --type json --headerline --file '^PROPERTY.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection PSEi --type json --headerline --file '^PSEi.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection SERVICE --type json --headerline --file '^SERVICE.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection ALPHA --type json --headerline --file 'ALPHA.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection BKD --type json --headerline --file 'BKD.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection COAT --type json --headerline --file 'COAT.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection NXT --type json --headerline --file 'NXT.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection PCKH --type json --headerline --file 'PCKH.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection SINO --type json --headerline --file 'SINO.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection ACPB --type json --headerline --file 'ACPB.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection MEGW1 --type json --headerline --file 'MEGW1.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection PORT --type json --headerline --file 'PORT.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection MAKE --type json --headerline --file 'MAKE.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection JSI --type json --headerline --file 'JSI.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection ACPA --type json --headerline --file 'ACPA.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection APM --type json --headerline --file 'APM.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection CLOUD --type json --headerline --file 'CLOUD.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection FPHP --type json --headerline --file 'FPHP.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection HP --type json --headerline --file 'HP.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection IP --type json --headerline --file 'IP.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection MIH --type json --headerline --file 'MIH.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection MIHB --type json --headerline --file 'MIHB.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection MMI --type json --headerline --file 'MMI.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection SMDC --type json --headerline --file 'SMDC.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection TSI --type json --headerline --file 'TSI.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection APXB --type json --headerline --file 'APXB.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection ICTV --type json --headerline --file 'ICTV.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection SENSEX --type json --headerline --file 'SENSEX.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection IRW --type json --headerline --file 'IRW.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection AAI --type json --headerline --file 'AAI.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection AMC --type json --headerline --file 'AMC.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection DGTL --type json --headerline --file 'DGTL.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection FMIC --type json --headerline --file 'FMIC.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection JTH --type json --headerline --file 'JTH.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection OMW2 --type json --headerline --file 'OMW2.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection PEP --type json --headerline --file 'PEP.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection RCM --type json --headerline --file 'RCM.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection SMB --type json --headerline --file 'SMB.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection SMCP1 --type json --headerline --file 'SMCP1.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection TDY --type json --headerline --file 'TDY.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection ATRK --type json --headerline --file 'ATRK.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection CHTR --type json --headerline --file 'CHTR.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection ETON --type json --headerline --file 'ETON.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection IRCB --type json --headerline --file 'IRCB.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection PCEV --type json --headerline --file 'PCEV.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection PO --type json --headerline --file 'PO.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection TOL --type json --headerline --file 'TOL.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection PECB --type json --headerline --file 'PECB.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection SMP --type json --headerline --file 'SMP.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection ATSP --type json --headerline --file 'ATSP.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection TWOGOP --type json --headerline --file '2GOP.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection PEC --type json --headerline --file 'PEC.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection ACPR --type json --headerline --file 'ACPR.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection ASIA --type json --headerline --file 'ASIA.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection UW --type json --headerline --file 'UW.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection EIBA --type json --headerline --file 'EIBA.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection EIBB --type json --headerline --file 'EIBB.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection SRDC --type json --headerline --file 'SRDC.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection PCP --type json --headerline --file 'PCP.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection GO --type json --headerline --file 'GO.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection DMCP --type json --headerline --file 'DMCP.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection GOB --type json --headerline --file 'GOB.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection FC --type json --headerline --file 'FC.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection PHC --type json --headerline --file 'PHC.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection MCB --type json --headerline --file 'MCB.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection MC --type json --headerline --file 'MC.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection MAHB --type json --headerline --file 'MAHB.json' -h 127.0.0.1:3001
mongoimport --db meteor --collection MAH --type json --headerline --file 'MAH.json' -h 127.0.0.1:3001
